stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt  # Install project dependencies
    - python -m unittest discover  # Run unit tests

deploy:
  stage: deploy
  script:
    - docker build -t lept0n5/mlops:$CI_COMMIT_SHORT_SHA .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push lept0n5/mlops:$CI_COMMIT_SHORT_SHA
